title: 'Gustavo Tobías | Portafolio'
author:
  name: 'Gustavo Adolfo Tobías Ramírez'
  email: 'tobiasgusito@gmail.com'
metadata:
    description: 'Portafolio profesional de Gustavo Adolfo Tobías Ramírez'
